version: "3.8"

services:
  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    volumes:
      - gruposimpli:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: LTyHbaUbov
volumes:
  gruposimpli:
